### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by mo13ammad** [aDarkDev/TelCoin-Script#18]
Please enter your phone (or bot token): 9************
Traceback (most recent call last):
  File "/root/TelCoin-Script/NotCoin.py", line 15, in <module>
    client = TelegramClient("cheat",api_id,api_hash).start()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 184, in _start
    await self.send_code_request(phone, force_sms=force_sms)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/auth.py", line 434, in send_code_request
    result = await self(functions.auth.SendCodeRequest(
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 30, in __call__
    return await self._call(self._sender, request, ordered=ordered)
  File "/usr/local/lib/python3.10/dist-packages/telethon/client/users.py", line 87, in _call
    result = await future
telethon.errors.rpcerrorlist.ApiIdInvalidError: The api_id/api_hash combination is invalid (caused by SendCodeRequest)
Segmentation fault (core dumped)

**Comment by aDarkDev** [comment]
telethon.errors.rpcerrorlist.ApiIdInvalidError
go to my.telegram.org and ger your api keys
