### ISSUE TITLE
The method you tried to invoke cannot be executed as a bot.

### ISSUE THREAD

**Issue by nnfoxeeee** [aDarkDev/TelCoin-Script#19]
Maybe the problem is on my end?
```
C:\Users\n***x\Desktop\TelCoin>python NotCoin.py
Traceback (most recent call last):
  File "C:\Users\n***x\Desktop\TelCoin\NotCoin.py", line 152, in <module>
	getAuthToken()
  File "C:\Users\n***x\Desktop\TelCoin\NotCoin.py", line 112, in getAuthToken
	client.loop.run_until_complete(GetWebAppData())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 685, in run_until_complete
	return future.result()
       	^^^^^^^^^^^^^^^
  File "C:\Users\n***x\Desktop\TelCoin\NotCoin.py", line 105, in GetWebAppData
	msg = await client(functions.messages.RequestWebViewRequest(notcoin,notcoin,platform="android",url="https://clicker.joincommunity.xyz/clicker"))
      	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\n***x\Users\\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\telethon\client\users.py", line 30, in call
	return await self._call(self._sender, request, ordered=ordered)
       	^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\n***x\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\telethon\client\users.py", line 87, in _call
	result = await future
         	^^^^^^^^^^^^
telethon.errors.rpcerrorlist.BotMethodInvalidError: The API access for bot users is restricted. The method you tried to invoke cannot be executed as a bot (caused by RequestWebViewRequest) ```

**Comment by aDarkDev** [comment]
use real account not bots
